spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
#    url: ${DB_URL}
    url: jdbc:postgresql://localhost:5432/Computer_sale_aplication
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          preferred_enum_type_postgres: true
        hbm2ddl:
          drop_unused_types: false
    show_sql: true
    hibernate:
      ddl-auto: update
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: trongho.373664@gmail.com
    template-id: ${TEMPLATE_ID}
    verification-link: http://localhost:8080/user/comfirm-email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: Computer_sell
    server: http://localhost:${server.port}
    title: Computer Sales Application
    version: 1.0.0
seller:
  name: "CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ THComputer"
  tax: "01234567891"
  address: "123 3/2 Phường Xuân Khánh, Quận Ninh Kiều, TP. Cần Thơ"
  phone: "0287123456"

vnpay:
  tmn-code: "3WKQT5FR"
  hash-secret: "0UE2G4R0Q2Y5CM0V1I5QJ20UPNIHJMDE"
  return-url: "http://localhost:5173/payment/vnpay-return"
  ipn-url: "http://localhost:8080/api/payments/vnpay/ipn"
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"




jwt:
  secretKey: abc@123
  expMinutes: 60
  expDate: 14
  accessKey: ${ACCESS_KEY}
  refreshKey: ${REFRESH_KEY}
